/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "./access";
export type { access };
import type * as amm from "./amm";
export type { amm };
import type * as core from "./core";
export type { core };
import type * as gambitToken from "./gambit-token";
export type { gambitToken };
import type * as gmx from "./gmx";
export type { gmx };
import type * as libraries from "./libraries";
export type { libraries };
import type * as oracle from "./oracle";
export type { oracle };
import type * as peripherals from "./peripherals";
export type { peripherals };
import type * as referrals from "./referrals";
export type { referrals };
import type * as staking from "./staking";
export type { staking };
import type * as tokens from "./tokens";
export type { tokens };
