/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IPositionRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decreasePositionRequestKeys"
      | "decreasePositionRequestKeysStart"
      | "executeDecreasePositions"
      | "executeIncreasePositions"
      | "getDecreasePositionRequestPath"
      | "getIncreasePositionRequestPath"
      | "getRequestQueueLengths"
      | "increasePositionRequestKeys"
      | "increasePositionRequestKeysStart"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "decreasePositionRequestKeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decreasePositionRequestKeysStart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeDecreasePositions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeIncreasePositions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecreasePositionRequestPath",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIncreasePositionRequestPath",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestQueueLengths",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "increasePositionRequestKeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increasePositionRequestKeysStart",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "decreasePositionRequestKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreasePositionRequestKeysStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeDecreasePositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeIncreasePositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecreasePositionRequestPath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIncreasePositionRequestPath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestQueueLengths",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increasePositionRequestKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increasePositionRequestKeysStart",
    data: BytesLike
  ): Result;
}

export interface IPositionRouter extends BaseContract {
  connect(runner?: ContractRunner | null): IPositionRouter;
  waitForDeployment(): Promise<this>;

  interface: IPositionRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decreasePositionRequestKeys: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  decreasePositionRequestKeysStart: TypedContractMethod<[], [bigint], "view">;

  executeDecreasePositions: TypedContractMethod<
    [_count: BigNumberish, _executionFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  executeIncreasePositions: TypedContractMethod<
    [_count: BigNumberish, _executionFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  getDecreasePositionRequestPath: TypedContractMethod<
    [_key: BytesLike],
    [string[]],
    "view"
  >;

  getIncreasePositionRequestPath: TypedContractMethod<
    [_key: BytesLike],
    [string[]],
    "view"
  >;

  getRequestQueueLengths: TypedContractMethod<
    [],
    [[bigint, bigint, bigint, bigint]],
    "view"
  >;

  increasePositionRequestKeys: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  increasePositionRequestKeysStart: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decreasePositionRequestKeys"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "decreasePositionRequestKeysStart"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeDecreasePositions"
  ): TypedContractMethod<
    [_count: BigNumberish, _executionFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeIncreasePositions"
  ): TypedContractMethod<
    [_count: BigNumberish, _executionFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDecreasePositionRequestPath"
  ): TypedContractMethod<[_key: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getIncreasePositionRequestPath"
  ): TypedContractMethod<[_key: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRequestQueueLengths"
  ): TypedContractMethod<[], [[bigint, bigint, bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "increasePositionRequestKeys"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "increasePositionRequestKeysStart"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
