/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1822Proxiable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1822Proxiable__factory>;
    getContractFactory(
      name: "IERC1967",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1967__factory>;
    getContractFactory(
      name: "BeaconProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BeaconProxy__factory>;
    getContractFactory(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBeacon__factory>;
    getContractFactory(
      name: "UpgradeableBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradeableBeacon__factory>;
    getContractFactory(
      name: "ERC1967Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Proxy__factory>;
    getContractFactory(
      name: "ERC1967Upgrade",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Upgrade__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "ProxyAdmin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProxyAdmin__factory>;
    getContractFactory(
      name: "ITransparentUpgradeableProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITransparentUpgradeableProxy__factory>;
    getContractFactory(
      name: "TransparentUpgradeableProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransparentUpgradeableProxy__factory>;
    getContractFactory(
      name: "Governable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Governable__factory>;
    getContractFactory(
      name: "IAdmin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAdmin__factory>;
    getContractFactory(
      name: "TokenManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenManager__factory>;
    getContractFactory(
      name: "IPancakeFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPancakeFactory__factory>;
    getContractFactory(
      name: "IPancakePair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPancakePair__factory>;
    getContractFactory(
      name: "IPancakeRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPancakeRouter__factory>;
    getContractFactory(
      name: "PancakeFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PancakeFactory__factory>;
    getContractFactory(
      name: "PancakePair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PancakePair__factory>;
    getContractFactory(
      name: "PancakeRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PancakeRouter__factory>;
    getContractFactory(
      name: "UniFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniFactory__factory>;
    getContractFactory(
      name: "UniNftManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniNftManager__factory>;
    getContractFactory(
      name: "UniPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniPool__factory>;
    getContractFactory(
      name: "BasePositionManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BasePositionManager__factory>;
    getContractFactory(
      name: "GlpManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GlpManager__factory>;
    getContractFactory(
      name: "IBasePositionManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBasePositionManager__factory>;
    getContractFactory(
      name: "IGlpManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGlpManager__factory>;
    getContractFactory(
      name: "IOrderBook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOrderBook__factory>;
    getContractFactory(
      name: "IPositionRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPositionRouter__factory>;
    getContractFactory(
      name: "IPositionRouterCallbackReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPositionRouterCallbackReceiver__factory>;
    getContractFactory(
      name: "IRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRouter__factory>;
    getContractFactory(
      name: "IShortsTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IShortsTracker__factory>;
    getContractFactory(
      name: "IVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVault__factory>;
    getContractFactory(
      name: "IVaultPriceFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVaultPriceFeed__factory>;
    getContractFactory(
      name: "IVaultUtils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVaultUtils__factory>;
    getContractFactory(
      name: "OrderBook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OrderBook__factory>;
    getContractFactory(
      name: "PositionManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PositionManager__factory>;
    getContractFactory(
      name: "PositionRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PositionRouter__factory>;
    getContractFactory(
      name: "PositionUtils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PositionUtils__factory>;
    getContractFactory(
      name: "Router",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Router__factory>;
    getContractFactory(
      name: "ShortsTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShortsTracker__factory>;
    getContractFactory(
      name: "PositionRouterCallbackReceiverTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PositionRouterCallbackReceiverTest__factory>;
    getContractFactory(
      name: "ShortsTrackerTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShortsTrackerTest__factory>;
    getContractFactory(
      name: "VaultTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultTest__factory>;
    getContractFactory(
      name: "Vault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Vault__factory>;
    getContractFactory(
      name: "VaultErrorController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultErrorController__factory>;
    getContractFactory(
      name: "VaultPriceFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultPriceFeed__factory>;
    getContractFactory(
      name: "VaultUtils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultUtils__factory>;
    getContractFactory(
      name: "GMT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GMT__factory>;
    getContractFactory(
      name: "IGMT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGMT__factory>;
    getContractFactory(
      name: "Treasury",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Treasury__factory>;
    getContractFactory(
      name: "EsGMX",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EsGMX__factory>;
    getContractFactory(
      name: "GLP",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GLP__factory>;
    getContractFactory(
      name: "GMX",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GMX__factory>;
    getContractFactory(
      name: "GmxFloor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GmxFloor__factory>;
    getContractFactory(
      name: "GmxIou",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GmxIou__factory>;
    getContractFactory(
      name: "GmxMigrator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GmxMigrator__factory>;
    getContractFactory(
      name: "IAmmRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAmmRouter__factory>;
    getContractFactory(
      name: "IGmxIou",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGmxIou__factory>;
    getContractFactory(
      name: "IGmxMigrator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGmxMigrator__factory>;
    getContractFactory(
      name: "MigrationHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MigrationHandler__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Enumerable__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "FastPriceEvents",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FastPriceEvents__factory>;
    getContractFactory(
      name: "FastPriceFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FastPriceFeed__factory>;
    getContractFactory(
      name: "IChainlinkFlags",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IChainlinkFlags__factory>;
    getContractFactory(
      name: "IFastPriceEvents",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFastPriceEvents__factory>;
    getContractFactory(
      name: "IFastPriceFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFastPriceFeed__factory>;
    getContractFactory(
      name: "IPriceFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPriceFeed__factory>;
    getContractFactory(
      name: "ISecondaryPriceFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISecondaryPriceFeed__factory>;
    getContractFactory(
      name: "PriceFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PriceFeed__factory>;
    getContractFactory(
      name: "BalanceUpdater",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BalanceUpdater__factory>;
    getContractFactory(
      name: "BatchSender",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BatchSender__factory>;
    getContractFactory(
      name: "EsGmxBatchSender",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EsGmxBatchSender__factory>;
    getContractFactory(
      name: "GmxTimelock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GmxTimelock__factory>;
    getContractFactory(
      name: "IGmxTimelock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGmxTimelock__factory>;
    getContractFactory(
      name: "IHandlerTarget",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHandlerTarget__factory>;
    getContractFactory(
      name: "ITimelock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITimelock__factory>;
    getContractFactory(
      name: "ITimelockTarget",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITimelockTarget__factory>;
    getContractFactory(
      name: "OrderBookReader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OrderBookReader__factory>;
    getContractFactory(
      name: "PositionRouterReader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PositionRouterReader__factory>;
    getContractFactory(
      name: "PriceFeedTimelock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PriceFeedTimelock__factory>;
    getContractFactory(
      name: "Reader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Reader__factory>;
    getContractFactory(
      name: "RewardReader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RewardReader__factory>;
    getContractFactory(
      name: "ShortsTrackerTimelock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShortsTrackerTimelock__factory>;
    getContractFactory(
      name: "Timelock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Timelock__factory>;
    getContractFactory(
      name: "VaultReader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultReader__factory>;
    getContractFactory(
      name: "IReferralStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IReferralStorage__factory>;
    getContractFactory(
      name: "ReferralReader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReferralReader__factory>;
    getContractFactory(
      name: "ReferralStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReferralStorage__factory>;
    getContractFactory(
      name: "BonusDistributor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BonusDistributor__factory>;
    getContractFactory(
      name: "GlpBalance",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GlpBalance__factory>;
    getContractFactory(
      name: "IRewardDistributor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRewardDistributor__factory>;
    getContractFactory(
      name: "IRewardRouterV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRewardRouterV2__factory>;
    getContractFactory(
      name: "IRewardTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRewardTracker__factory>;
    getContractFactory(
      name: "IVester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVester__factory>;
    getContractFactory(
      name: "RewardDistributor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RewardDistributor__factory>;
    getContractFactory(
      name: "RewardRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RewardRouter__factory>;
    getContractFactory(
      name: "RewardRouterV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RewardRouterV2__factory>;
    getContractFactory(
      name: "RewardTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RewardTracker__factory>;
    getContractFactory(
      name: "StakedGlp",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StakedGlp__factory>;
    getContractFactory(
      name: "StakedGlpMigrator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StakedGlpMigrator__factory>;
    getContractFactory(
      name: "StakeManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StakeManager__factory>;
    getContractFactory(
      name: "Vester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Vester__factory>;
    getContractFactory(
      name: "BaseToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseToken__factory>;
    getContractFactory(
      name: "Bridge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Bridge__factory>;
    getContractFactory(
      name: "FaucetToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FaucetToken__factory>;
    getContractFactory(
      name: "IBaseToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBaseToken__factory>;
    getContractFactory(
      name: "IBridge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBridge__factory>;
    getContractFactory(
      name: "IDistributor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDistributor__factory>;
    getContractFactory(
      name: "IGLP",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGLP__factory>;
    getContractFactory(
      name: "IMintable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMintable__factory>;
    getContractFactory(
      name: "IUSDG",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUSDG__factory>;
    getContractFactory(
      name: "IWETH",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWETH__factory>;
    getContractFactory(
      name: "IYieldToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IYieldToken__factory>;
    getContractFactory(
      name: "IYieldTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IYieldTracker__factory>;
    getContractFactory(
      name: "MintableBaseToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MintableBaseToken__factory>;
    getContractFactory(
      name: "SnapshotToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SnapshotToken__factory>;
    getContractFactory(
      name: "TimeDistributor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TimeDistributor__factory>;
    getContractFactory(
      name: "Token",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Token__factory>;
    getContractFactory(
      name: "USDG",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.USDG__factory>;
    getContractFactory(
      name: "WETH",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WETH__factory>;
    getContractFactory(
      name: "YieldFarm",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YieldFarm__factory>;
    getContractFactory(
      name: "YieldToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YieldToken__factory>;
    getContractFactory(
      name: "YieldTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YieldTracker__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1822Proxiable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1822Proxiable>;
    getContractAt(
      name: "IERC1967",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1967>;
    getContractAt(
      name: "BeaconProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BeaconProxy>;
    getContractAt(
      name: "IBeacon",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBeacon>;
    getContractAt(
      name: "UpgradeableBeacon",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradeableBeacon>;
    getContractAt(
      name: "ERC1967Proxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967Proxy>;
    getContractAt(
      name: "ERC1967Upgrade",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967Upgrade>;
    getContractAt(
      name: "Proxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "ProxyAdmin",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ProxyAdmin>;
    getContractAt(
      name: "ITransparentUpgradeableProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITransparentUpgradeableProxy>;
    getContractAt(
      name: "TransparentUpgradeableProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransparentUpgradeableProxy>;
    getContractAt(
      name: "Governable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Governable>;
    getContractAt(
      name: "IAdmin",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAdmin>;
    getContractAt(
      name: "TokenManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenManager>;
    getContractAt(
      name: "IPancakeFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPancakeFactory>;
    getContractAt(
      name: "IPancakePair",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPancakePair>;
    getContractAt(
      name: "IPancakeRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPancakeRouter>;
    getContractAt(
      name: "PancakeFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PancakeFactory>;
    getContractAt(
      name: "PancakePair",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PancakePair>;
    getContractAt(
      name: "PancakeRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PancakeRouter>;
    getContractAt(
      name: "UniFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.UniFactory>;
    getContractAt(
      name: "UniNftManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.UniNftManager>;
    getContractAt(
      name: "UniPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.UniPool>;
    getContractAt(
      name: "BasePositionManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BasePositionManager>;
    getContractAt(
      name: "GlpManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GlpManager>;
    getContractAt(
      name: "IBasePositionManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBasePositionManager>;
    getContractAt(
      name: "IGlpManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGlpManager>;
    getContractAt(
      name: "IOrderBook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IOrderBook>;
    getContractAt(
      name: "IPositionRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPositionRouter>;
    getContractAt(
      name: "IPositionRouterCallbackReceiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPositionRouterCallbackReceiver>;
    getContractAt(
      name: "IRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRouter>;
    getContractAt(
      name: "IShortsTracker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IShortsTracker>;
    getContractAt(
      name: "IVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVault>;
    getContractAt(
      name: "IVaultPriceFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVaultPriceFeed>;
    getContractAt(
      name: "IVaultUtils",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVaultUtils>;
    getContractAt(
      name: "OrderBook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OrderBook>;
    getContractAt(
      name: "PositionManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PositionManager>;
    getContractAt(
      name: "PositionRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PositionRouter>;
    getContractAt(
      name: "PositionUtils",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PositionUtils>;
    getContractAt(
      name: "Router",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Router>;
    getContractAt(
      name: "ShortsTracker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ShortsTracker>;
    getContractAt(
      name: "PositionRouterCallbackReceiverTest",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PositionRouterCallbackReceiverTest>;
    getContractAt(
      name: "ShortsTrackerTest",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ShortsTrackerTest>;
    getContractAt(
      name: "VaultTest",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultTest>;
    getContractAt(
      name: "Vault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Vault>;
    getContractAt(
      name: "VaultErrorController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultErrorController>;
    getContractAt(
      name: "VaultPriceFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultPriceFeed>;
    getContractAt(
      name: "VaultUtils",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultUtils>;
    getContractAt(
      name: "GMT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GMT>;
    getContractAt(
      name: "IGMT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGMT>;
    getContractAt(
      name: "Treasury",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Treasury>;
    getContractAt(
      name: "EsGMX",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EsGMX>;
    getContractAt(
      name: "GLP",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GLP>;
    getContractAt(
      name: "GMX",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GMX>;
    getContractAt(
      name: "GmxFloor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GmxFloor>;
    getContractAt(
      name: "GmxIou",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GmxIou>;
    getContractAt(
      name: "GmxMigrator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GmxMigrator>;
    getContractAt(
      name: "IAmmRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAmmRouter>;
    getContractAt(
      name: "IGmxIou",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGmxIou>;
    getContractAt(
      name: "IGmxMigrator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGmxMigrator>;
    getContractAt(
      name: "MigrationHandler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MigrationHandler>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "IERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Enumerable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Enumerable>;
    getContractAt(
      name: "IERC721Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "FastPriceEvents",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FastPriceEvents>;
    getContractAt(
      name: "FastPriceFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FastPriceFeed>;
    getContractAt(
      name: "IChainlinkFlags",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IChainlinkFlags>;
    getContractAt(
      name: "IFastPriceEvents",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFastPriceEvents>;
    getContractAt(
      name: "IFastPriceFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFastPriceFeed>;
    getContractAt(
      name: "IPriceFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPriceFeed>;
    getContractAt(
      name: "ISecondaryPriceFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISecondaryPriceFeed>;
    getContractAt(
      name: "PriceFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PriceFeed>;
    getContractAt(
      name: "BalanceUpdater",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BalanceUpdater>;
    getContractAt(
      name: "BatchSender",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BatchSender>;
    getContractAt(
      name: "EsGmxBatchSender",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EsGmxBatchSender>;
    getContractAt(
      name: "GmxTimelock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GmxTimelock>;
    getContractAt(
      name: "IGmxTimelock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGmxTimelock>;
    getContractAt(
      name: "IHandlerTarget",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHandlerTarget>;
    getContractAt(
      name: "ITimelock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITimelock>;
    getContractAt(
      name: "ITimelockTarget",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITimelockTarget>;
    getContractAt(
      name: "OrderBookReader",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OrderBookReader>;
    getContractAt(
      name: "PositionRouterReader",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PositionRouterReader>;
    getContractAt(
      name: "PriceFeedTimelock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PriceFeedTimelock>;
    getContractAt(
      name: "Reader",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Reader>;
    getContractAt(
      name: "RewardReader",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RewardReader>;
    getContractAt(
      name: "ShortsTrackerTimelock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ShortsTrackerTimelock>;
    getContractAt(
      name: "Timelock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Timelock>;
    getContractAt(
      name: "VaultReader",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultReader>;
    getContractAt(
      name: "IReferralStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IReferralStorage>;
    getContractAt(
      name: "ReferralReader",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReferralReader>;
    getContractAt(
      name: "ReferralStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReferralStorage>;
    getContractAt(
      name: "BonusDistributor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BonusDistributor>;
    getContractAt(
      name: "GlpBalance",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GlpBalance>;
    getContractAt(
      name: "IRewardDistributor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRewardDistributor>;
    getContractAt(
      name: "IRewardRouterV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRewardRouterV2>;
    getContractAt(
      name: "IRewardTracker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRewardTracker>;
    getContractAt(
      name: "IVester",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVester>;
    getContractAt(
      name: "RewardDistributor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RewardDistributor>;
    getContractAt(
      name: "RewardRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RewardRouter>;
    getContractAt(
      name: "RewardRouterV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RewardRouterV2>;
    getContractAt(
      name: "RewardTracker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RewardTracker>;
    getContractAt(
      name: "StakedGlp",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StakedGlp>;
    getContractAt(
      name: "StakedGlpMigrator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StakedGlpMigrator>;
    getContractAt(
      name: "StakeManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StakeManager>;
    getContractAt(
      name: "Vester",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Vester>;
    getContractAt(
      name: "BaseToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseToken>;
    getContractAt(
      name: "Bridge",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Bridge>;
    getContractAt(
      name: "FaucetToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FaucetToken>;
    getContractAt(
      name: "IBaseToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBaseToken>;
    getContractAt(
      name: "IBridge",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBridge>;
    getContractAt(
      name: "IDistributor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDistributor>;
    getContractAt(
      name: "IGLP",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGLP>;
    getContractAt(
      name: "IMintable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMintable>;
    getContractAt(
      name: "IUSDG",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IUSDG>;
    getContractAt(
      name: "IWETH",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWETH>;
    getContractAt(
      name: "IYieldToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IYieldToken>;
    getContractAt(
      name: "IYieldTracker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IYieldTracker>;
    getContractAt(
      name: "MintableBaseToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MintableBaseToken>;
    getContractAt(
      name: "SnapshotToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SnapshotToken>;
    getContractAt(
      name: "TimeDistributor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TimeDistributor>;
    getContractAt(
      name: "Token",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Token>;
    getContractAt(
      name: "USDG",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.USDG>;
    getContractAt(
      name: "WETH",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WETH>;
    getContractAt(
      name: "YieldFarm",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.YieldFarm>;
    getContractAt(
      name: "YieldToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.YieldToken>;
    getContractAt(
      name: "YieldTracker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.YieldTracker>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1822Proxiable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1822Proxiable>;
    deployContract(
      name: "IERC1967",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1967>;
    deployContract(
      name: "BeaconProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BeaconProxy>;
    deployContract(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "UpgradeableBeacon",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UpgradeableBeacon>;
    deployContract(
      name: "ERC1967Proxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Proxy>;
    deployContract(
      name: "ERC1967Upgrade",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Upgrade>;
    deployContract(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Proxy>;
    deployContract(
      name: "ProxyAdmin",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProxyAdmin>;
    deployContract(
      name: "ITransparentUpgradeableProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITransparentUpgradeableProxy>;
    deployContract(
      name: "TransparentUpgradeableProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransparentUpgradeableProxy>;
    deployContract(
      name: "Governable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Governable>;
    deployContract(
      name: "IAdmin",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAdmin>;
    deployContract(
      name: "TokenManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenManager>;
    deployContract(
      name: "IPancakeFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeFactory>;
    deployContract(
      name: "IPancakePair",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakePair>;
    deployContract(
      name: "IPancakeRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeRouter>;
    deployContract(
      name: "PancakeFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PancakeFactory>;
    deployContract(
      name: "PancakePair",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PancakePair>;
    deployContract(
      name: "PancakeRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PancakeRouter>;
    deployContract(
      name: "UniFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UniFactory>;
    deployContract(
      name: "UniNftManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UniNftManager>;
    deployContract(
      name: "UniPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UniPool>;
    deployContract(
      name: "BasePositionManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BasePositionManager>;
    deployContract(
      name: "GlpManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GlpManager>;
    deployContract(
      name: "IBasePositionManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBasePositionManager>;
    deployContract(
      name: "IGlpManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGlpManager>;
    deployContract(
      name: "IOrderBook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOrderBook>;
    deployContract(
      name: "IPositionRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPositionRouter>;
    deployContract(
      name: "IPositionRouterCallbackReceiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPositionRouterCallbackReceiver>;
    deployContract(
      name: "IRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRouter>;
    deployContract(
      name: "IShortsTracker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IShortsTracker>;
    deployContract(
      name: "IVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVault>;
    deployContract(
      name: "IVaultPriceFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVaultPriceFeed>;
    deployContract(
      name: "IVaultUtils",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVaultUtils>;
    deployContract(
      name: "OrderBook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrderBook>;
    deployContract(
      name: "PositionManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PositionManager>;
    deployContract(
      name: "PositionRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PositionRouter>;
    deployContract(
      name: "PositionUtils",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PositionUtils>;
    deployContract(
      name: "Router",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Router>;
    deployContract(
      name: "ShortsTracker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortsTracker>;
    deployContract(
      name: "PositionRouterCallbackReceiverTest",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PositionRouterCallbackReceiverTest>;
    deployContract(
      name: "ShortsTrackerTest",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortsTrackerTest>;
    deployContract(
      name: "VaultTest",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultTest>;
    deployContract(
      name: "Vault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Vault>;
    deployContract(
      name: "VaultErrorController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultErrorController>;
    deployContract(
      name: "VaultPriceFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultPriceFeed>;
    deployContract(
      name: "VaultUtils",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultUtils>;
    deployContract(
      name: "GMT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GMT>;
    deployContract(
      name: "IGMT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGMT>;
    deployContract(
      name: "Treasury",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Treasury>;
    deployContract(
      name: "EsGMX",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EsGMX>;
    deployContract(
      name: "GLP",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GLP>;
    deployContract(
      name: "GMX",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GMX>;
    deployContract(
      name: "GmxFloor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GmxFloor>;
    deployContract(
      name: "GmxIou",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GmxIou>;
    deployContract(
      name: "GmxMigrator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GmxMigrator>;
    deployContract(
      name: "IAmmRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAmmRouter>;
    deployContract(
      name: "IGmxIou",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGmxIou>;
    deployContract(
      name: "IGmxMigrator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGmxMigrator>;
    deployContract(
      name: "MigrationHandler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MigrationHandler>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Enumerable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Enumerable>;
    deployContract(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "FastPriceEvents",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FastPriceEvents>;
    deployContract(
      name: "FastPriceFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FastPriceFeed>;
    deployContract(
      name: "IChainlinkFlags",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IChainlinkFlags>;
    deployContract(
      name: "IFastPriceEvents",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastPriceEvents>;
    deployContract(
      name: "IFastPriceFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastPriceFeed>;
    deployContract(
      name: "IPriceFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPriceFeed>;
    deployContract(
      name: "ISecondaryPriceFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISecondaryPriceFeed>;
    deployContract(
      name: "PriceFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PriceFeed>;
    deployContract(
      name: "BalanceUpdater",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BalanceUpdater>;
    deployContract(
      name: "BatchSender",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BatchSender>;
    deployContract(
      name: "EsGmxBatchSender",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EsGmxBatchSender>;
    deployContract(
      name: "GmxTimelock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GmxTimelock>;
    deployContract(
      name: "IGmxTimelock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGmxTimelock>;
    deployContract(
      name: "IHandlerTarget",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHandlerTarget>;
    deployContract(
      name: "ITimelock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITimelock>;
    deployContract(
      name: "ITimelockTarget",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITimelockTarget>;
    deployContract(
      name: "OrderBookReader",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrderBookReader>;
    deployContract(
      name: "PositionRouterReader",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PositionRouterReader>;
    deployContract(
      name: "PriceFeedTimelock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PriceFeedTimelock>;
    deployContract(
      name: "Reader",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Reader>;
    deployContract(
      name: "RewardReader",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardReader>;
    deployContract(
      name: "ShortsTrackerTimelock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortsTrackerTimelock>;
    deployContract(
      name: "Timelock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Timelock>;
    deployContract(
      name: "VaultReader",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultReader>;
    deployContract(
      name: "IReferralStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReferralStorage>;
    deployContract(
      name: "ReferralReader",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReferralReader>;
    deployContract(
      name: "ReferralStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReferralStorage>;
    deployContract(
      name: "BonusDistributor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BonusDistributor>;
    deployContract(
      name: "GlpBalance",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GlpBalance>;
    deployContract(
      name: "IRewardDistributor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRewardDistributor>;
    deployContract(
      name: "IRewardRouterV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRewardRouterV2>;
    deployContract(
      name: "IRewardTracker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRewardTracker>;
    deployContract(
      name: "IVester",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVester>;
    deployContract(
      name: "RewardDistributor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardDistributor>;
    deployContract(
      name: "RewardRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardRouter>;
    deployContract(
      name: "RewardRouterV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardRouterV2>;
    deployContract(
      name: "RewardTracker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardTracker>;
    deployContract(
      name: "StakedGlp",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakedGlp>;
    deployContract(
      name: "StakedGlpMigrator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakedGlpMigrator>;
    deployContract(
      name: "StakeManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakeManager>;
    deployContract(
      name: "Vester",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Vester>;
    deployContract(
      name: "BaseToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseToken>;
    deployContract(
      name: "Bridge",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Bridge>;
    deployContract(
      name: "FaucetToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FaucetToken>;
    deployContract(
      name: "IBaseToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBaseToken>;
    deployContract(
      name: "IBridge",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBridge>;
    deployContract(
      name: "IDistributor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDistributor>;
    deployContract(
      name: "IGLP",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGLP>;
    deployContract(
      name: "IMintable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMintable>;
    deployContract(
      name: "IUSDG",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IUSDG>;
    deployContract(
      name: "IWETH",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWETH>;
    deployContract(
      name: "IYieldToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IYieldToken>;
    deployContract(
      name: "IYieldTracker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IYieldTracker>;
    deployContract(
      name: "MintableBaseToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MintableBaseToken>;
    deployContract(
      name: "SnapshotToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SnapshotToken>;
    deployContract(
      name: "TimeDistributor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TimeDistributor>;
    deployContract(
      name: "Token",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Token>;
    deployContract(
      name: "USDG",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.USDG>;
    deployContract(
      name: "WETH",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WETH>;
    deployContract(
      name: "YieldFarm",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldFarm>;
    deployContract(
      name: "YieldToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldToken>;
    deployContract(
      name: "YieldTracker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldTracker>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1822Proxiable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1822Proxiable>;
    deployContract(
      name: "IERC1967",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1967>;
    deployContract(
      name: "BeaconProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BeaconProxy>;
    deployContract(
      name: "IBeacon",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "UpgradeableBeacon",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UpgradeableBeacon>;
    deployContract(
      name: "ERC1967Proxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Proxy>;
    deployContract(
      name: "ERC1967Upgrade",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Upgrade>;
    deployContract(
      name: "Proxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Proxy>;
    deployContract(
      name: "ProxyAdmin",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProxyAdmin>;
    deployContract(
      name: "ITransparentUpgradeableProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITransparentUpgradeableProxy>;
    deployContract(
      name: "TransparentUpgradeableProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransparentUpgradeableProxy>;
    deployContract(
      name: "Governable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Governable>;
    deployContract(
      name: "IAdmin",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAdmin>;
    deployContract(
      name: "TokenManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenManager>;
    deployContract(
      name: "IPancakeFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeFactory>;
    deployContract(
      name: "IPancakePair",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakePair>;
    deployContract(
      name: "IPancakeRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPancakeRouter>;
    deployContract(
      name: "PancakeFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PancakeFactory>;
    deployContract(
      name: "PancakePair",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PancakePair>;
    deployContract(
      name: "PancakeRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PancakeRouter>;
    deployContract(
      name: "UniFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UniFactory>;
    deployContract(
      name: "UniNftManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UniNftManager>;
    deployContract(
      name: "UniPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UniPool>;
    deployContract(
      name: "BasePositionManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BasePositionManager>;
    deployContract(
      name: "GlpManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GlpManager>;
    deployContract(
      name: "IBasePositionManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBasePositionManager>;
    deployContract(
      name: "IGlpManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGlpManager>;
    deployContract(
      name: "IOrderBook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOrderBook>;
    deployContract(
      name: "IPositionRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPositionRouter>;
    deployContract(
      name: "IPositionRouterCallbackReceiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPositionRouterCallbackReceiver>;
    deployContract(
      name: "IRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRouter>;
    deployContract(
      name: "IShortsTracker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IShortsTracker>;
    deployContract(
      name: "IVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVault>;
    deployContract(
      name: "IVaultPriceFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVaultPriceFeed>;
    deployContract(
      name: "IVaultUtils",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVaultUtils>;
    deployContract(
      name: "OrderBook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrderBook>;
    deployContract(
      name: "PositionManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PositionManager>;
    deployContract(
      name: "PositionRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PositionRouter>;
    deployContract(
      name: "PositionUtils",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PositionUtils>;
    deployContract(
      name: "Router",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Router>;
    deployContract(
      name: "ShortsTracker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortsTracker>;
    deployContract(
      name: "PositionRouterCallbackReceiverTest",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PositionRouterCallbackReceiverTest>;
    deployContract(
      name: "ShortsTrackerTest",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortsTrackerTest>;
    deployContract(
      name: "VaultTest",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultTest>;
    deployContract(
      name: "Vault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Vault>;
    deployContract(
      name: "VaultErrorController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultErrorController>;
    deployContract(
      name: "VaultPriceFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultPriceFeed>;
    deployContract(
      name: "VaultUtils",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultUtils>;
    deployContract(
      name: "GMT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GMT>;
    deployContract(
      name: "IGMT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGMT>;
    deployContract(
      name: "Treasury",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Treasury>;
    deployContract(
      name: "EsGMX",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EsGMX>;
    deployContract(
      name: "GLP",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GLP>;
    deployContract(
      name: "GMX",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GMX>;
    deployContract(
      name: "GmxFloor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GmxFloor>;
    deployContract(
      name: "GmxIou",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GmxIou>;
    deployContract(
      name: "GmxMigrator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GmxMigrator>;
    deployContract(
      name: "IAmmRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAmmRouter>;
    deployContract(
      name: "IGmxIou",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGmxIou>;
    deployContract(
      name: "IGmxMigrator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGmxMigrator>;
    deployContract(
      name: "MigrationHandler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MigrationHandler>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Enumerable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Enumerable>;
    deployContract(
      name: "IERC721Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "FastPriceEvents",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FastPriceEvents>;
    deployContract(
      name: "FastPriceFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FastPriceFeed>;
    deployContract(
      name: "IChainlinkFlags",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IChainlinkFlags>;
    deployContract(
      name: "IFastPriceEvents",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastPriceEvents>;
    deployContract(
      name: "IFastPriceFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastPriceFeed>;
    deployContract(
      name: "IPriceFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPriceFeed>;
    deployContract(
      name: "ISecondaryPriceFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISecondaryPriceFeed>;
    deployContract(
      name: "PriceFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PriceFeed>;
    deployContract(
      name: "BalanceUpdater",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BalanceUpdater>;
    deployContract(
      name: "BatchSender",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BatchSender>;
    deployContract(
      name: "EsGmxBatchSender",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EsGmxBatchSender>;
    deployContract(
      name: "GmxTimelock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GmxTimelock>;
    deployContract(
      name: "IGmxTimelock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGmxTimelock>;
    deployContract(
      name: "IHandlerTarget",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHandlerTarget>;
    deployContract(
      name: "ITimelock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITimelock>;
    deployContract(
      name: "ITimelockTarget",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITimelockTarget>;
    deployContract(
      name: "OrderBookReader",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrderBookReader>;
    deployContract(
      name: "PositionRouterReader",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PositionRouterReader>;
    deployContract(
      name: "PriceFeedTimelock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PriceFeedTimelock>;
    deployContract(
      name: "Reader",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Reader>;
    deployContract(
      name: "RewardReader",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardReader>;
    deployContract(
      name: "ShortsTrackerTimelock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortsTrackerTimelock>;
    deployContract(
      name: "Timelock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Timelock>;
    deployContract(
      name: "VaultReader",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultReader>;
    deployContract(
      name: "IReferralStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReferralStorage>;
    deployContract(
      name: "ReferralReader",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReferralReader>;
    deployContract(
      name: "ReferralStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReferralStorage>;
    deployContract(
      name: "BonusDistributor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BonusDistributor>;
    deployContract(
      name: "GlpBalance",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GlpBalance>;
    deployContract(
      name: "IRewardDistributor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRewardDistributor>;
    deployContract(
      name: "IRewardRouterV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRewardRouterV2>;
    deployContract(
      name: "IRewardTracker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRewardTracker>;
    deployContract(
      name: "IVester",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVester>;
    deployContract(
      name: "RewardDistributor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardDistributor>;
    deployContract(
      name: "RewardRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardRouter>;
    deployContract(
      name: "RewardRouterV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardRouterV2>;
    deployContract(
      name: "RewardTracker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardTracker>;
    deployContract(
      name: "StakedGlp",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakedGlp>;
    deployContract(
      name: "StakedGlpMigrator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakedGlpMigrator>;
    deployContract(
      name: "StakeManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakeManager>;
    deployContract(
      name: "Vester",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Vester>;
    deployContract(
      name: "BaseToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseToken>;
    deployContract(
      name: "Bridge",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Bridge>;
    deployContract(
      name: "FaucetToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FaucetToken>;
    deployContract(
      name: "IBaseToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBaseToken>;
    deployContract(
      name: "IBridge",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBridge>;
    deployContract(
      name: "IDistributor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDistributor>;
    deployContract(
      name: "IGLP",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGLP>;
    deployContract(
      name: "IMintable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMintable>;
    deployContract(
      name: "IUSDG",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IUSDG>;
    deployContract(
      name: "IWETH",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWETH>;
    deployContract(
      name: "IYieldToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IYieldToken>;
    deployContract(
      name: "IYieldTracker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IYieldTracker>;
    deployContract(
      name: "MintableBaseToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MintableBaseToken>;
    deployContract(
      name: "SnapshotToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SnapshotToken>;
    deployContract(
      name: "TimeDistributor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TimeDistributor>;
    deployContract(
      name: "Token",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Token>;
    deployContract(
      name: "USDG",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.USDG>;
    deployContract(
      name: "WETH",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WETH>;
    deployContract(
      name: "YieldFarm",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldFarm>;
    deployContract(
      name: "YieldToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldToken>;
    deployContract(
      name: "YieldTracker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldTracker>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
