/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PositionUtilsInterface extends Interface {
  getFunction(nameOrSignature: "BASIS_POINTS_DIVISOR"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LeverageDecreased"): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS_DIVISOR",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS_DIVISOR",
    data: BytesLike
  ): Result;
}

export namespace LeverageDecreasedEvent {
  export type InputTuple = [
    collateralDelta: BigNumberish,
    prevLeverage: BigNumberish,
    nextLeverage: BigNumberish
  ];
  export type OutputTuple = [
    collateralDelta: bigint,
    prevLeverage: bigint,
    nextLeverage: bigint
  ];
  export interface OutputObject {
    collateralDelta: bigint;
    prevLeverage: bigint;
    nextLeverage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PositionUtils extends BaseContract {
  connect(runner?: ContractRunner | null): PositionUtils;
  waitForDeployment(): Promise<this>;

  interface: PositionUtilsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS_DIVISOR: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS_DIVISOR"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "LeverageDecreased"
  ): TypedContractEvent<
    LeverageDecreasedEvent.InputTuple,
    LeverageDecreasedEvent.OutputTuple,
    LeverageDecreasedEvent.OutputObject
  >;

  filters: {
    "LeverageDecreased(uint256,uint256,uint256)": TypedContractEvent<
      LeverageDecreasedEvent.InputTuple,
      LeverageDecreasedEvent.OutputTuple,
      LeverageDecreasedEvent.OutputObject
    >;
    LeverageDecreased: TypedContractEvent<
      LeverageDecreasedEvent.InputTuple,
      LeverageDecreasedEvent.OutputTuple,
      LeverageDecreasedEvent.OutputObject
    >;
  };
}
